x-backend-environment: &backend-environment
  SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${HANGMAN_DB}
  SPRING_DATASOURCE_USERNAME: ${HANGMAN_DB_USER}
  SPRING_DATASOURCE_PASSWORD: ${HANGMAN_DB_PASSWORD}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update

services:
  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    expose:
      - "80"
    restart: always
    networks:
      - hangman_network

  backend-1:
    container_name: hangman-backend-1
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    environment:
      INIT_DATABASE: "true"
      <<: *backend-environment
    expose:
      - "8080"
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - hangman_network

  backend-2:
    container_name: hangman-backend-2
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    environment:
      <<: *backend-environment
    expose:
      - "8080"
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - hangman_network

  backend-3:
    container_name: hangman-backend-3
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    environment:
      <<: *backend-environment
    expose:
      - "8080"
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - hangman_network

  mysqldb:
    image: mysql:8.0
    container_name: hangman-mysqldb
    environment:
      MYSQL_DATABASE: ${HANGMAN_DB}
      MYSQL_USER: ${HANGMAN_DB_USER}
      MYSQL_PASSWORD: ${HANGMAN_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${HANGMAN_DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hangman_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${HANGMAN_DB_USER} -p${HANGMAN_DB_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  nginx:
    image: nginx:latest
    container_name: hangman-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" # Change here if not port 80
    depends_on:
      - frontend
      - backend-1
      - backend-2
      - backend-3
    networks:
      - hangman_network
    restart: always

volumes:
  mysql_data:

networks:
  hangman_network:
    driver: bridge
