services:
  frontend:
    container_name: frontend
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  backend1:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend-1
    ports:
      - "8091:8080"
    environment:
      INIT_DATABASE: TRUE
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${HANGMAN_DB}
      SPRING_DATASOURCE_USERNAME: ${HANGMAN_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${HANGMAN_DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysqldb:
        condition: service_healthy

  backend2:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend-2
    ports:
      - "8092:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${HANGMAN_DB}
      SPRING_DATASOURCE_USERNAME: ${HANGMAN_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${HANGMAN_DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysqldb:
        condition: service_healthy

  backend3:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend-3
    ports:
      - "8093:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${HANGMAN_DB}
      SPRING_DATASOURCE_USERNAME: ${HANGMAN_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${HANGMAN_DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
    restart: always
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${HANGMAN_DB}
      MYSQL_USER: ${HANGMAN_DB_USER}
      MYSQL_PASSWORD: ${HANGMAN_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${HANGMAN_DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - backend1
      - backend2
      - backend3

volumes:
  mysql_data:
