name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and start Docker containers
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Run tests (optional)
      run: |
        # Hier kannst du deine Testbefehle hinzufügen
        # z.B. curl -f http://localhost:8080/health
        echo "Tests erfolgreich"
